from sznk.repository.repository import Repository
from sznk.repository.lecture_repository import LectureRepository
from sznk.repository.user_repository import UserRepository
from sznk.repository.lecture_repository import LectureRepository
from sznk.repository.lecturer_repository import LecturerRepository
